name: 'Docker Build & Push'
description: 'Build Docker image and push to any registry'

inputs:
  registry:
    description: 'Registry URL (e.g., docker.io, ghcr.io, 123456.dkr.ecr.region.amazonaws.com)'
    required: true
  repository:
    description: 'Repository name (e.g., myorg/myapp)'
    required: true
  image-tag:
    description: 'Image tag'
    required: true
  extra-tags:
    description: 'Extra tags (newline separated)'
    required: false
    default: ''
  dockerfile:
    description: 'Dockerfile path'
    required: false
    default: 'Dockerfile'
  target:
    description: 'Docker build target'
    required: false
    default: 'final'
  build-args:
    description: 'Build arguments (multiline KEY=VALUE)'
    required: false
    default: ''
  maven-settings-path:
    description: 'Path to Maven settings.xml (Docker secret)'
    required: false
    default: ''

outputs:
  image-uri:
    description: 'Full image URI'
    value: ${{ steps.output.outputs.uri }}
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - uses: docker/setup-buildx-action@v3

    - name: Build tags
      id: tags
      shell: bash
      run: |
        BASE="${{ inputs.registry }}/${{ inputs.repository }}"
        TAGS="${BASE}:${{ inputs.image-tag }}"
        if [ -n "${{ inputs.extra-tags }}" ]; then
          while IFS= read -r tag; do
            [ -n "$tag" ] && TAGS="${TAGS}
        ${BASE}:${tag}"
          done <<< "${{ inputs.extra-tags }}"
        fi
        echo "tags<<EOF" >> $GITHUB_OUTPUT
        echo "$TAGS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        target: ${{ inputs.target }}
        push: true
        tags: ${{ steps.tags.outputs.tags }}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        secrets: |
          maven_settings=${{ inputs.maven-settings-path }}

    - name: Output URI
      id: output
      shell: bash
      run: |
        echo "uri=${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT
