name: 'Docker Test'
description: 'Run tests via Docker build target'

inputs:
  dockerfile:
    description: 'Dockerfile path'
    required: false
    default: 'Dockerfile'
  target:
    description: 'Docker build target for tests'
    required: false
    default: 'test'
  maven-settings-path:
    description: 'Path to Maven settings.xml'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: docker/setup-buildx-action@v3

    - name: Run tests
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        target: ${{ inputs.target }}
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        secrets: |
          maven_settings=${{ inputs.maven-settings-path }}
